name: Driftctl AWS Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials
      - name: Set up AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}  
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/config
          echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/config
          echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/config
          echo "region = ${AWS_REGION}" >> ~/.aws/config  # Add region to config

          # Debugging: Print AWS configuration (DO NOT print sensitive values)
          cat ~/.aws/config

      # Step 3: Download and Install Driftctl
      - name: Download Driftctl
        run: |
          curl -L https://github.com/snyk/driftctl/releases/latest/download/driftctl_linux_amd64 -o driftctl
          chmod +x driftctl
          sudo mv driftctl /usr/local/bin/

      # Step 4: Verify Driftctl Installation
      - name: Verify Driftctl Installation
        run: |
          driftctl version

      # Step 5: Run Driftctl Scan against AWS
      - name: Run Driftctl Scan
        run: |
          echo "Running Driftctl scan against AWS..."
          driftctl scan --from tfstate://terraform.tfstate --to aws+tf --output console:// || true
