name: Driftctl Workflow

on:
  push:
    branches:
      - main

jobs:
  driftctl:
    name: Run Driftctl
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Driftctl
      - name: Install Driftctl
        run: |
          # Download the Driftctl binary
          curl -Lo driftctl https://github.com/snyk/driftctl/releases/latest/download/driftctl-linux-amd64
          
          # Verify the file was downloaded
          if [ ! -f driftctl ]; then
            echo "Driftctl binary not downloaded!"
            exit 1
          fi

          # Check the file size to ensure it's not empty
          FILESIZE=$(stat -c%s "driftctl")
          if [ "$FILESIZE" -lt 100 ]; then
            echo "Downloaded Driftctl binary is too small: ${FILESIZE} bytes. Possible download error."
            exit 1
          fi

          # Make it executable
          chmod +x driftctl

          # Move it to a local bin directory
          sudo mv driftctl /usr/local/bin/

          # Verify if Driftctl is in PATH
          echo "Verifying Driftctl installation..."
          if ! command -v driftctl &> /dev/null; then
            echo "Driftctl installation failed: driftctl command not found"
            exit 1
          fi

      # Step 3: Configure AWS Credentials
      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "AWS credentials set"

      # Step 4: Verify Driftctl Installation
      - name: Verify Driftctl Installation
        run: |
          echo "Checking Driftctl version..."
          driftctl version || (echo "Driftctl command failed"; exit 1)

      # Step 5: Run Driftctl Scan
      - name: Run Driftctl Scan
        run: |
          driftctl scan --from tfstate://path/to/your/terraform.tfstate --to aws+tf
